import { type Metadata } from 'next'
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs'
import { Bricolage_Grotesque, PT_Serif } from 'next/font/google'
import './globals.css'

const bricolage = Bricolage_Grotesque({
    subsets: ['latin'],
    variable: '--font-bricolage',
    display: 'swap',
})

const ptSerif = PT_Serif({
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    variable: '--font-pt-serif',
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
            <html lang="fr" data-theme="light" className={`${bricolage.variable} ${ptSerif.variable}`}>
                <title>Aquarium</title>
                <body className={bricolage.className}>
                    <ClerkProvider>
                        {children}
                    </ClerkProvider>
                </body>
            </html>
    )
}